# Generated by Django 3.1.4 on 2021-02-05 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=250)),
                ('course_photo', models.ImageField(blank=True, default='course_image/default.jpg', upload_to='course_image/')),
                ('preview_video_id', models.CharField(max_length=350)),
                ('course_category', models.ManyToManyField(to='course.course_category')),
            ],
        ),
        migrations.CreateModel(
            name='lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=250)),
                ('lesson_photo', models.ImageField(blank=True, default='course_image/default.jpg', upload_to='course_image/')),
                ('lesson_video_id', models.CharField(max_length=350)),
                ('lesson_description', models.CharField(max_length=350)),
                ('lesson_code', models.CharField(max_length=350)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
    ]
