# Generated by Django 3.1.4 on 2021-02-05 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20210205_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_title',
            new_name='course_tittle',
        ),
    ]
