# Generated by Django 3.1.4 on 2021-02-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20210205_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_slug',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
