# Generated by Django 3.1.4 on 2021-02-10 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_access_to_course_requirements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_requirements',
            old_name='requirment',
            new_name='requirement',
        ),
    ]
