# Generated by Django 3.1.4 on 2021-02-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20210219_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='lesson_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.CharField(max_length=250)),
                ('comment', models.CharField(blank=True, max_length=250)),
                ('user_email', models.CharField(blank=True, max_length=250)),
                ('user_name', models.CharField(blank=True, max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='lesson_comment_reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_comment_id', models.CharField(max_length=250)),
                ('comment', models.CharField(blank=True, max_length=250)),
                ('user_email', models.CharField(blank=True, max_length=250)),
                ('user_name', models.CharField(blank=True, max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
