# Generated by Django 3.1.4 on 2021-02-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_tittle', models.CharField(blank=True, max_length=250)),
                ('blog_by', models.CharField(blank=True, max_length=250)),
                ('blog_description', models.CharField(blank=True, max_length=250)),
                ('blog_photo', models.ImageField(blank=True, upload_to='course_image/')),
                ('blog_slug', models.SlugField(max_length=250, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('blog_category', models.ManyToManyField(to='blog.blog_category')),
            ],
        ),
    ]
