# Generated by Django 3.1.4 on 2021-02-23 09:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_description',
            field=tinymce.models.HTMLField(),
        ),
    ]
