# Generated by Django 3.1.4 on 2021-02-23 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210223_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_descriptions',
            new_name='blog_description',
        ),
    ]
