# Generated by Django 3.1.4 on 2021-02-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_comment_blog_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_name',
            field=models.CharField(blank=True, default='No Name', max_length=250),
        ),
    ]
