# Generated by Django 3.1.4 on 2021-02-24 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_blog_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_comment_reply',
            old_name='blog_id',
            new_name='blog_comment_id',
        ),
    ]
