# Generated by Django 3.1.4 on 2021-03-04 08:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210224_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
