# Generated by Django 3.1.4 on 2021-01-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='age',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='gender',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='phone',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
