# Generated by Django 3.1.4 on 2021-02-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificate/'),
        ),
    ]
