# Generated by Django 3.1.4 on 2021-03-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_certificate_certificate_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='message',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
