# Generated by Django 3.1.4 on 2021-03-04 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='content',
            new_name='text',
        ),
    ]
