# Generated by Django 3.1.4 on 2021-03-04 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210304_1339'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
